print("First 10 letters in lower case:")
t=head(letters,10)
print(t)
t=tail("Last 10 letters in upper case")
t=tail(letters,10)
print(t)
print("Letters between 22 and 24 letters in upper case:")
e=tail(letters[22:24])
print(e)