M1= matrix(1:20,nrow=5,ncol=4)
print("5X4 MATRIX")
print(M1)
cells=c(1,3,5,7,9,11,12,14)
rnames=c("Row1","Row2","Row3")
cnames=c("Col1","Col2","Col3")
M2 = matrix(cells,nrow=3,ncol=3,byrow=TRUE,dimnames=list(rnames,cnames))
print("3 x 3 matrix with label,filled by rows:")
print(M2)
print("3 x 3 matrix with label,filled by columns:") 
M3 = matrix(cells,nrow=3,ncol=3,byrow=FALSE,dimnames=list(rnames,cnames))
print(M3)